CREATE NODE TABLE IF NOT EXISTS Artifact(name STRING, kind STRING, path STRING, PRIMARY KEY(name));
CREATE NODE TABLE IF NOT EXISTS Module(name STRING, kind STRING, PRIMARY KEY(name));
CREATE REL TABLE IF NOT EXISTS DEPENDS_ON(FROM Module TO Module);
CREATE REL TABLE IF NOT EXISTS DOCUMENTS(FROM Artifact TO Module);

